# Generated by Django 5.2.9 on 2025-12-04 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecore', '0002_contact_jobapplication_studyapplication_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LookFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='lookfiles/')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='sitecore.contact')),
            ],
        ),
    ]
